repos:
  # basic pre-commit hooks
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: end-of-file-fixer

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports
        args: [ --py37-plus, --add-import, 'from __future__ import annotations' ]


  # detecting and removing unused imports with unimport
  #- repo: https://github.com/hakancelik96/unimport
  #  rev: 0.2.7
  #  hooks:
  #    - id: unimport
  #      args: [-r, --include-star-import]
  #      files: "\\.(py)$"

  # enforcing the use of new python syntax with pyupgrade
  #- repo: https://github.com/asottile/pyupgrade
  #  rev: v2.7.2
  #  hooks:
  #    - id: pyupgrade

  # code formatting with black
  - repo: 'https://github.com/psf/black'
    rev: 23.1.0
    hooks:
      - id: black
        args: [--line-length=160,]
        language_version: python3


  # linting and code analysis with flake8
  #- repo: https://gitlab.com/pycqa/flake8
  #  rev: 3.8.3
  #  hooks:
  #    - id: flake8
  #      args: [--max-line-length=160, --ignore=E203 E231 E800 W503 ANN101 ANN102 ANN204 N806 N803 N802]
  #      additional_dependencies: [flake8-bugbear, flake8-comprehensions, flake8-eradicate, pep8-naming, flake8-annotations]

  # type checking with mypy
  #- repo: 'https://github.com/pre-commit/mirrors-mypy'
  #  rev: v1.4.1
  #  hooks:
  #    - id: mypy
